export const asset = (name) => new URL(`./assets/${name}`, import.meta.url).href;
export const fallbackProducts = [
  {
    id: 1,
    name: 'Vestido Floral Encantado',
    slug: 'vestido-floral-encantado',
    price: 89.9,
    stock: 18,
    category: { name: 'Meninas', slug: 'meninas' },
    featured: true,
    image: 'colecao-produtos.png',
    tone: 'coral',
  },
  {
    id: 2,
    name: 'Polo Listrada Aventura',
    slug: 'polo-listrada-aventura',
    price: 69.9,
    stock: 12,
    category: { name: 'Meninos', slug: 'meninos' },
    featured: true,
    new: true,
    image: 'colecao-produtos.png',
    tone: 'blue',
  },
  {
    id: 3,
    name: 'Jardineira Jeans Divertida',
    slug: 'jardineira-jeans-divertida',
    price: 99.9,
    salePrice: 84.9,
    stock: 7,
    category: { name: 'Meninos', slug: 'meninos' },
    featured: true,
    promotion: true,
    image: 'colecao-produtos.png',
    tone: 'denim',
  },
  {
    id: 4,
    name: 'Camiseta Dino Explorador',
    slug: 'camiseta-dino-explorador',
    price: 49.9,
    stock: 4,
    category: { name: 'Meninos', slug: 'meninos' },
    featured: true,
    new: true,
    image: 'colecao-produtos.png',
    tone: 'yellow',
  },
  {
    id: 5,
    name: 'Bermuda Moletom Conforto',
    slug: 'bermuda-moletom-conforto',
    price: 59.9,
    stock: 10,
    category: { name: 'Meninos', slug: 'meninos' },
    featured: true,
    image: 'colecao-produtos.png',
    tone: 'shorts',
  },
  {
    id: 6,
    name: 'Vestido Arco-Íris',
    slug: 'vestido-arco-iris',
    price: 94.9,
    stock: 15,
    category: { name: 'Meninas', slug: 'meninas' },
    new: true,
    image: 'colecao-produtos.png',
    tone: 'coral',
  },
  {
    id: 7,
    name: 'Conjunto Natureza',
    slug: 'conjunto-natureza',
    price: 79.9,
    stock: 9,
    category: { name: 'Meninas', slug: 'meninas' },
    new: true,
    image: 'colecao-produtos.png',
    tone: 'blue',
  },
  {
    id: 8,
    name: 'Moletom Ursinho',
    slug: 'moletom-ursinho',
    price: 89.9,
    stock: 5,
    category: { name: 'Bebê', slug: 'bebe' },
    new: true,
    image: 'colecao-produtos.png',
    tone: 'yellow',
  },
  {
    id: 9,
    name: 'Jaqueta Jeans',
    slug: 'jaqueta-jeans',
    price: 119.9,
    salePrice: 99.9,
    stock: 2,
    category: { name: 'Meninos', slug: 'meninos' },
    new: true,
    promotion: true,
    image: 'colecao-produtos.png',
    tone: 'denim',
  },
  {
    id: 10,
    name: 'Calça Jogger Rosa',
    slug: 'calca-jogger-rosa',
    price: 59.9,
    stock: 11,
    category: { name: 'Meninas', slug: 'meninas' },
    new: true,
    image: 'colecao-produtos.png',
    tone: 'shorts',
  },
];
export const categories = [
  ['Vestidos', 'Sparkles', 'meninas', '#ffe478'],
  ['Conjuntos', 'Shirt', 'meninas', '#dff3fd'],
  ['Blusas', 'Shirt', 'meninas', '#ffe6ed'],
  ['Calças', 'BriefcaseBusiness', 'meninos', '#dff3fd'],
  ['Shorts', 'CircleDot', 'meninos', '#dff6e7'],
  ['Acessórios', 'Backpack', 'acessorios', '#ffebd8'],
  ['Calçados', 'Footprints', 'acessorios', '#f4efff'],
  ['Bebê', 'Baby', 'bebe', '#eee9ff'],
];
